# src/main/resorces/application-local.properties

# Perfil para ejecutar todo en modo local

# ===== Spring =====
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=dev_user
spring.datasource.password=${DB_PASSWORD}

# ===== Server =====
server.port=8080
