ALTER TABLE users ADD COLUMN first_name VARCHAR(120);
ALTER TABLE users ADD COLUMN last_name VARCHAR(120);
ALTER TABLE users ADD COLUMN dni VARCHAR(20);
ALTER TABLE users ADD COLUMN birth_date DATE;
ALTER TABLE users ADD COLUMN phone VARCHAR(40);
ALTER TABLE users ADD COLUMN country VARCHAR(100);
ALTER TABLE users ADD COLUMN province VARCHAR(100);
ALTER TABLE users ADD COLUMN address VARCHAR(255);
ALTER TABLE users ADD COLUMN terms_accepted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN profile_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN auth_provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE users ADD COLUMN google_subject VARCHAR(255);
ALTER TABLE users ADD COLUMN picture_url VARCHAR(500);

CREATE UNIQUE INDEX ux_users_dni_present ON users (dni) WHERE dni IS NOT NULL;
CREATE UNIQUE INDEX ux_users_google_subject_present ON users (google_subject) WHERE google_subject IS NOT NULL;
